[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true

[theme]
primaryColor = "#45A9F9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1e1e2e"
font = "monospace"


